### PR TITLE
Overhaul `IntersectionPoint`

### PR DESCRIPTION
**Pull request by nhwn**
This avoids issues caused by aliasing restrictions, which allows us to remove some unnecessary box allocations. I went ahead and made the fields `pub(crate)` since adding setters seems like overkill for the number of use-cases we have.

### CODE REVIEW

**Comment by nhwn** [comment]
this is sus code

**Comment by nhwn** [comment]
just kidding

**Comment by tcheinen** [comment]
I think it looks pretty good; is there anything in specific you'd like me to focus on when reviewing?

**Comment by VTCAKAVSMoACE** [comment]
Nah just go ham, look for anything which obviously doesn't need recomputing or the like.

**Comment by VTCAKAVSMoACE** [comment]
I'm merging this and there's nothing you can do to stop me

**Pull request merged**
